### ISSUE TITLE
File protocol in import URL

### ISSUE THREAD

**Issue by janekx21** [janekx21/owl-ms-language-server#33]
**As a** user,
**I want to** import other ontologies using the file protocol,
**so that** a local file is used without the catalog.

## Subtasks
- Add file protocol to import resolve
- Take a look at workspace resolution for these files

## DoD
- The example ontology below works

## Backgound 

https://github.com/janekx21/owl-ms-language-server/pull/31#issuecomment-2858038111

Example:
a.omn: as above but saved in `/tmp/a.omn`
b.omn:
```
Ontology:

Import: <file:///tmp/a.omn>

Class: B *B (b.omn)*
    Annotations: rdfs:label "B (b.omn)"
    SubClassOf: A <-- no inlay here
```
